# ../Vagrantfile will use this config file to build a cloud with 2 HA
# controllers and 0 compute nodes.  You'll probably need at least 8GB
# RAM on the host for this!
---
networks:
  management: 192.168.101.0/24  # FIXME: currently only used for libvirt
  crowbar:
    admin_ip: 192.168.124.10
    pool_start: 192.168.124.80  # temporary; prior to crowbar_register.sh
vms:
  - name: DEFAULT
    cpus: 2
    ram: 2200
    box: suse/sles11sp3
  - name: admin
    personality: admin
    primary: true
    ram: 2000
    box: suse/cloud4-admin
    forward_ports:
      - {host: 3000, guest: 3000}  # Crowbar admin web UI
  - name: controller1
    personality: controller
    drbd: true
    sbd: create
    glance-nfs: true
    forward_ports:
      - {host: 7630, guest: 7630}  # Hawk web UI for HA clusters
  - name: controller2
    personality: controller
    drbd: true
    sbd: share
    glance-nfs: true
    forward_ports:
      - {host: 7631, guest: 7630}  # Hawk web UI for HA clusters
